version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: movies-client
    container_name: movies-nuxt-client
    ports:
      - '3000:3000'
    restart: always
